# This is a basic workflow to help you get started with Actions

name: Hello World
on: push
jobs: 
  hello-job:
    runs-on: ubuntu-latest
    steps:

      - name: Echo text
        run: 'echo "Hello, world!"'
